import { invariant } from './errors.mjs';

export const JOB_STATUS = Object.freeze({
  DRAFT: 'DRAFT',
  OPEN: 'OPEN',
  ASSIGNED: 'ASSIGNED',
  IN_PROGRESS: 'IN_PROGRESS',
  SUBMITTED: 'SUBMITTED',
  UNDER_VERIFICATION: 'UNDER_VERIFICATION',
  COMPLETED: 'COMPLETED',
  DISPUTED: 'DISPUTED',
  REFUNDED: 'REFUNDED',
  CANCELLED: 'CANCELLED',
  EXPIRED: 'EXPIRED'
});

const TRANSITIONS = new Map([
  [JOB_STATUS.DRAFT, new Set([JOB_STATUS.OPEN, JOB_STATUS.CANCELLED])],
  [JOB_STATUS.OPEN, new Set([JOB_STATUS.ASSIGNED, JOB_STATUS.CANCELLED, JOB_STATUS.EXPIRED])],
  [JOB_STATUS.ASSIGNED, new Set([JOB_STATUS.OPEN, JOB_STATUS.IN_PROGRESS, JOB_STATUS.CANCELLED])],
  [JOB_STATUS.IN_PROGRESS, new Set([JOB_STATUS.SUBMITTED, JOB_STATUS.OPEN, JOB_STATUS.DISPUTED])],
  [JOB_STATUS.SUBMITTED, new Set([JOB_STATUS.UNDER_VERIFICATION, JOB_STATUS.DISPUTED])],
  [JOB_STATUS.UNDER_VERIFICATION, new Set([JOB_STATUS.COMPLETED, JOB_STATUS.DISPUTED, JOB_STATUS.REFUNDED])],
  [JOB_STATUS.DISPUTED, new Set([JOB_STATUS.COMPLETED, JOB_STATUS.REFUNDED])]
]);

export function assertTransition(current, next) {
  const allowed = TRANSITIONS.get(current) ?? new Set();
  invariant(allowed.has(next), 'INVALID_JOB_TRANSITION', `Cannot transition job from ${current} to ${next}.`, 409, {
    current,
    next,
    allowed: [...allowed]
  });
}
